baseURL: "https://learn-computer-graphics.com/"
title: Learn Computer Graphics
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: G-0R4K11ZRKP

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Mathematics
      url: /mathematics/
      weight: 2
    - name: Machine Learning
      url: /machine-learning/
      weight: 3
    - name: Tags
      url: /tags/
      weight: 4
    - name: Archives
      url: /archives/
      weight: 5

params:
  env: production
  description: "Articles and classes to generate and extract data from images"
  author: Learn Computer Graphics team
  ShowReadingTime: true
  defaultTheme: auto
  ShowShareButtons: true
  defaultTheme: light
  disableThemeToggle: true
  displayFullLangName: true

  homeInfoParams:
    Title: "Be Visual 🖼️"
    Content: We'll help you to befriend art and science through articles and interactive exercices 

  socialIcons:
    - name: github
      url: "https://github.com/learn-computer-graphics"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: false
    simple: true

  twitter:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
