baseURL: "https://learn-computer-graphics.com/"
title: Learn Computer Graphics
paginate: 8
theme: hugo-PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

googleAnalytics: UA-180280643-1

minify:
  disableXML: true
  minifyOutput: true

menu:
  main:
    - identifier: blog
      name: Blog
      url: /
      weight: 1
    - name: Tags
      parent: blog
      url: /tags/
      weight: 1
    - name: Archives
      parent: blog
      url: /archives/
      weight: 2
    - name: Maths
      url: /mathematics/
      weight: 2
    - name: AI
      url: /machine-learning/
      weight: 3
    - name: Graphics
      url: /rendering-techniques/
      weight: 3

params:
  env: production
  description: "Articles and classes to generate and extract data from images"
  author: Learn Computer Graphics team
  defaultTheme: light
  disableThemeToggle: true
  displayFullLangName: true
  ShowReadingTime: true
  ShowShareButtons: false
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true

  homeInfoParams:
    Title: "Be Visual 🖼️"
    Content: We'll help you to befriend art and science through articles and interactive exercices 

  socialIcons:
    - name: github
      url: "https://github.com/learn-computer-graphics"
    - name: rss
      url: "https://github.com/learn-computer-graphics/blog/commits.atom"

taxonomies:
  category: categories
  tag: tags
  series: series

privacy:
  vimeo:
    disabled: true
    simple: true

  twitter:
    disabled: true
    enableDNT: true
    simple: true

  instagram:
    disabled: true
    simple: true

  youtube:
    disabled: true
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
