name: ftp deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.91.2'
          # extended: true

      - name: Build
        run: hugo -d blog --minify

      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftp.cluster023.hosting.ovh.net
          username: guillaumpm
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./blog/
          server-dir: blog/
